- name: ensure unison user exists
  ansible.builtin.user:
    name: unison
    shell: /bin/bash
  become: true

- name: deploy management scripts
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '~unison/{{ item }}'
    mode: 0755
    owner: unison
    group: unison
  loop:
    - 'clear_old_dailys'
    - 'mkbackup'
  become: true

- name: monthly archive backup cron
  ansible.builtin.cron:
    name: "monthly archive sync-backup"
    minute: 0
    hour: 1
    day: "1"
    job: "~unison/mkbackup MONTHLY"
    user: unison
  become: true


- name: daily backup cron
  ansible.builtin.cron:
    name: "take daily sync-backup"
    minute: 0
    hour: 1
    day: "2-31"
    job: "~unison/mkbackup DAILY"
    user: unison
  become: true

- name: daily cleanup cron
  ansible.builtin.cron:
    name: "remove old daily backups"
    minute: 0
    hour: 2
    job: "~unison/clear_old_dailys"
    user: unison
  become: true

